spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.110.128/mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-coupon
mybatis-plus:
  #告诉mybatisplus xml文件在哪
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      #主键自增
      id-type: auto
      # 配置服务端口号
server:
  port: 7000